#page title
page_title: The Countdown

# App Info
ios_app_id: 6503321562
ios_app_country: us 

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:

app_icon: assets/icon.png
app_name: The Countdown
app_price: Free # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: The Countdown is a simple and easy-to-use app that helps you keep track of important events and such as birthdays, weddings or vacations.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Stepan Zalis
your_link: https://twitter.com/stepanzalis
your_city: Prague
email_address: stepan.zalis@gmail.com
facebook_username:
instagram_username:
twitter_username: stepanzalis
github_username: stepanzalis
youtube_username:
mastodon_link:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Effortless Event Tracking
    description: Quickly set up countdowns for all your important events. From birthdays and anniversaries to project deadlines and travel plans, TheCountdown makes it easy to stay organized and never miss a moment. Simply input the event date, and let TheCountdown handle the rest.
    fontawesome_icon_name: calendar-alt

  - title: Personalized Widget Designs
    description: Customize your home screen with beautifully designed countdown widgets. Choose from a range of styles, colors, and fonts to match your personal taste.
    fontawesome_icon_name: paint-brush

  - title: Recurring Events
    description: Automatically repeat events on your schedule. Set up daily, weekly, monthly, or yearly reminders for events like birthdays, anniversaries, and more.
    fontawesome_icon_name: sync-alt

  - title: Photo Backgrounds
    description: Personalize your countdowns with custom photo backgrounds. Upload your own pictures or choose from our curated gallery to make each countdown truly yours.
    fontawesome_icon_name: image

  - title: Real-time Sync Across Devices
    description: Stay updated no matter where you are. With real-time syncing, your countdowns are always available across all your devices.
    fontawesome_icon_name: cloud

  - title: Secure Data Backup
    description: Your data is safe with us. TheCountdown offers secure cloud storage and automatic backups, ensuring that your important dates and details are never lost.
    fontawesome_icon_name: lock

# Theme Settings
topbar_color: "#F37335"
topbar_transparency: 1.0
topbar_title_color: "#ffffff"

cover_image: assets/header.png # Replace with alternative image path or image URL.
cover_overlay_color: "#00ffffff"
cover_overlay_transparency: 0.0

device_color: countdown

body_background_color: "#ffffff"

link_color: "#000000"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#000000"

feature_icons_foreground_color: "#ffffff"
feature_icons_background_color: "#F37335"

social_icons_foreground_color: "#ffffff"
social_icons_background_color: "#F37335"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
# sass:
  # style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
